### ISSUE TITLE
Zoom (mouse scroll) does not work in Chrome, Edge

### ISSUE THREAD

**Issue by joebobmiles** [repeated-pleasant-games/tabletop#10]
In Chrome, zooming in via mouse scroll zooms in _way_ too far too be useful. Hard to tell what's going on with zooming out, but the grid totally disappears and the origin jumps to the mouse cursor.

In Edge, zooming in works somewhat as expected (though still too much to be useful). However, when zooming out the grid goes black and, similar to Chrome, the origin jumps to the mouse cursor.

**Comment by JoeBobMiles** [comment]
Found some links that will be helpful:
1. Facebook's archived [fixed-data-table repository](https://github.com/facebookarchive/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js)
1. [A StackOverflow question](https://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers) about normalizing scroll wheel deltas. (From which we got the above link.)
