### ISSUE TITLE
Create continuous deployment pipeline with GitHub Actions

### ISSUE THREAD

**Issue by joebobmiles** [repeated-pleasant-games/tabletop#12]

**Comment by JoeBobMiles** [comment]
Currently setup a temporary deployment using DigitalOcean's free app deployment system. Later we're going to switch over to either self-hosting or JAMStack, which will require setting up deployment via GitHub Actions.

**Comment by joebobmiles** [comment]
I need to create a new deployment. DigitalOcean, for some reason, dropped me from their system and now there is a zombie deployment of the application. It still updates, but I have no idea how long that will last.

We currently have our own webserver, so we can self-host the application.

**Comment by joebobmiles** [comment]
Self-hosting is done, but automatic deployment is going to be involved.

**Comment by joebobmiles** [comment]
Automatic deployment has been implemented
